Update NEOFORGE_VERSION to 21.1.219
The following error is appearing at startup:

```
[22:31:01] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Mod fabric_sound_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_recipe_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_item_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_networking_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_object_builder_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_renderer_indigo requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_loot_api_v2 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_rendering_data_attachment_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_data_attachment_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_resource_loader_v0 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_model_loading_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_loot_api_v3 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_gametest_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_command_api_v2 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_biome_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod ferritecore requires neoforge 21.1.218 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_block_view_api_v2 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_entity_events_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_game_rule_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_block_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_screen_handler_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_api_lookup_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_api_base requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_data_generation_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_lifecycle_events_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_particles_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_item_group_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_key_binding_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_client_tags_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_transitive_access_wideners_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_content_registries_v0 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_convention_tags_v2 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_events_interaction_v0 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_transfer_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_rendering_fluids_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_convention_tags_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_renderer_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_screen_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_resource_conditions_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_blockrenderlayer_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_rendering_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_registry_sync_v0 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209

        - Mod fabric_message_api_v1 requires neoforge 21.1.219 or above
          Currently, neoforge is 21.1.209
```